name: Java CI

on: [pull_request, push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run Gradle Tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check 
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
